namespace: ansible
name: vultr
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/ansible.vultr.git
documentation: https://github.com/coll-test/ansible.vultr/tree/master/docs
homepage: https://github.com/coll-test/ansible.vultr
issues: https://github.com/coll-test/ansible.vultr/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
